apiVersion: v1
kind: Pod
metadata:
  generateName: app-
spec:
  containers:
    - name: cpu
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do :; done"]
      resources:
        requests:
          cpu: "100m"
